# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "comfy_gallery"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oleg Khabarov", "Stephen McLeod", "The Working Group Inc."]
  s.date = "2012-02-22"
  s.description = ""
  s.email = "oleg@twg.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/comfy_gallery/border.png",
    "app/assets/images/comfy_gallery/controls.png",
    "app/assets/images/comfy_gallery/jcrop.gif",
    "app/assets/images/comfy_gallery/loading.gif",
    "app/assets/images/comfy_gallery/loading_background.png",
    "app/assets/images/comfy_gallery/overlay.png",
    "app/assets/javascripts/comfy_gallery/jquery.colorbox.js",
    "app/assets/javascripts/comfy_gallery/jquery.jcrop.js",
    "app/assets/stylesheets/comfy_gallery/colorbox.css",
    "app/assets/stylesheets/comfy_gallery/jquery.jcrop.css",
    "app/controllers/admin/gallery/base_controller.rb",
    "app/controllers/admin/gallery/galleries_controller.rb",
    "app/controllers/admin/gallery/photos_controller.rb",
    "app/controllers/application_controller.rb",
    "app/helpers/gallery/application_helper.rb",
    "app/models/gallery/gallery.rb",
    "app/models/gallery/photo.rb",
    "app/views/admin/gallery/_navigation.html.erb",
    "app/views/admin/gallery/galleries/_form.html.erb",
    "app/views/admin/gallery/galleries/edit.html.erb",
    "app/views/admin/gallery/galleries/index.html.erb",
    "app/views/admin/gallery/galleries/new.html.erb",
    "app/views/admin/gallery/photos/_form.html.erb",
    "app/views/admin/gallery/photos/crop.html.erb",
    "app/views/admin/gallery/photos/edit.html.erb",
    "app/views/admin/gallery/photos/index.html.erb",
    "app/views/admin/gallery/photos/new.html.erb",
    "app/views/layouts/gallery/application.html.erb",
    "comfy_gallery.gemspec",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/comfy_gallery.rb",
    "config/initializers/paperclip.rb",
    "config/routes.rb",
    "db/migrate/01_create_comfy_gallery.rb",
    "lib/comfy_gallery.rb",
    "lib/comfy_gallery/configuration.rb",
    "lib/comfy_gallery/engine.rb",
    "lib/comfy_gallery/form_builder.rb",
    "lib/generators/comfy/gallery/README",
    "lib/generators/comfy/gallery/gallery_generator.rb",
    "lib/paperclip_processors/cropper.rb",
    "lib/tasks/comfy_gallery.rake",
    "script/rails",
    "sofa_gallery.gemspec",
    "test/fixtures/files/default.jpg",
    "test/fixtures/files/default.txt",
    "test/fixtures/files/default2.jpg",
    "test/fixtures/gallery/galleries.yml",
    "test/fixtures/gallery/photos.yml",
    "test/functional/admin/gallery/galleries_controller_test.rb",
    "test/functional/admin/gallery/photos_controller_test.rb",
    "test/test_helper.rb",
    "test/unit/configuration_test.rb",
    "test/unit/gallery_test.rb",
    "test/unit/photo_test.rb"
  ]
  s.homepage = "http://github.com/comfy/comfy-gallery"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "ComfyGallery is an image gallery engine for Rails 3.1 apps (and ComfortableMexicanSofa)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 1.0.14"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<paperclip>, [">= 2.3.0"])
      s.add_dependency(%q<jquery-rails>, [">= 1.0.14"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<paperclip>, [">= 2.3.0"])
    s.add_dependency(%q<jquery-rails>, [">= 1.0.14"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

