# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "comfy_gallery"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oleg Khabarov", "Stephen McLeod", "The Working Group Inc."]
  s.date = "2012-02-10"
  s.description = ""
  s.email = "oleg@twg.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/comfy_gallery/jcrop.gif",
    "app/assets/images/comfy_gallery/orbit/bullets.jpg",
    "app/assets/images/comfy_gallery/orbit/left-arrow.png",
    "app/assets/images/comfy_gallery/orbit/loading.gif",
    "app/assets/images/comfy_gallery/orbit/mask-black.png",
    "app/assets/images/comfy_gallery/orbit/pause-black.png",
    "app/assets/images/comfy_gallery/orbit/right-arrow.png",
    "app/assets/images/comfy_gallery/orbit/rotator-black.png",
    "app/assets/images/comfy_gallery/orbit/timer-black.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/btnNext.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/btnPrevious.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/contentPattern.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/default_thumbnail.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_rounded/sprite.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/btnNext.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/btnPrevious.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/contentPattern.png",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/default_thumbnail.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/dark_square/sprite.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/default_thumb.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/default/sprite.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/sprite_next.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/sprite_prev.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/sprite_x.png",
    "app/assets/images/comfy_gallery/prettyPhoto/default/sprite_y.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/btnNext.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/btnPrevious.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/contentPatternBottom.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/contentPatternLeft.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/contentPatternRight.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/contentPatternTop.png",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/default_thumbnail.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/facebook/sprite.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_rounded/btnNext.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_rounded/btnPrevious.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_rounded/default_thumbnail.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/light_rounded/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/light_rounded/sprite.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_square/btnNext.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_square/btnPrevious.png",
    "app/assets/images/comfy_gallery/prettyPhoto/light_square/default_thumbnail.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/light_square/loader.gif",
    "app/assets/images/comfy_gallery/prettyPhoto/light_square/sprite.png",
    "app/assets/javascripts/comfy_gallery/admin.js",
    "app/assets/javascripts/comfy_gallery/application.js",
    "app/assets/javascripts/comfy_gallery/jquery.jcrop.js",
    "app/assets/javascripts/comfy_gallery/jquery.orbit-1.2.3.min.js",
    "app/assets/javascripts/comfy_gallery/thumbnails.js",
    "app/assets/stylesheets/comfy_gallery/admin.css",
    "app/assets/stylesheets/comfy_gallery/application.css",
    "app/assets/stylesheets/comfy_gallery/carousel.css.erb",
    "app/assets/stylesheets/comfy_gallery/gallery_list.css",
    "app/assets/stylesheets/comfy_gallery/jquery.jcrop.css",
    "app/assets/stylesheets/comfy_gallery/reset.css",
    "app/assets/stylesheets/comfy_gallery/thumbnails.css.erb",
    "app/controllers/admin/gallery/base_controller.rb",
    "app/controllers/admin/gallery/galleries_controller.rb",
    "app/controllers/admin/gallery/photos_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/gallery/galleries_controller.rb",
    "app/helpers/gallery/application_helper.rb",
    "app/models/gallery/gallery.rb",
    "app/models/gallery/photo.rb",
    "app/views/admin/gallery/_html_head.html.erb",
    "app/views/admin/gallery/_navigation.html.erb",
    "app/views/admin/gallery/galleries/_form.html.erb",
    "app/views/admin/gallery/galleries/edit.html.erb",
    "app/views/admin/gallery/galleries/index.html.erb",
    "app/views/admin/gallery/galleries/new.html.erb",
    "app/views/admin/gallery/photos/_form.html.erb",
    "app/views/admin/gallery/photos/crop.html.erb",
    "app/views/admin/gallery/photos/edit.html.erb",
    "app/views/admin/gallery/photos/index.html.erb",
    "app/views/admin/gallery/photos/new.html.erb",
    "app/views/gallery/_carousel.html.erb",
    "app/views/gallery/_list_galleries.html.erb",
    "app/views/gallery/_thumbnails.html.erb",
    "app/views/gallery/galleries/index.html.erb",
    "app/views/gallery/galleries/show.html.erb",
    "app/views/layouts/gallery/application.html.erb",
    "comfy_gallery.gemspec",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/comfy_gallery.rb",
    "config/initializers/paperclip.rb",
    "config/routes.rb",
    "db/migrate/01_create_comfy_gallery.rb",
    "lib/comfy_gallery.rb",
    "lib/comfy_gallery/configuration.rb",
    "lib/comfy_gallery/engine.rb",
    "lib/comfy_gallery/form_builder.rb",
    "lib/generators/comfy/gallery/README",
    "lib/generators/comfy/gallery/gallery_generator.rb",
    "lib/paperclip_processors/cropper.rb",
    "lib/tasks/comfy_gallery.rake",
    "script/rails",
    "sofa_gallery.gemspec",
    "test/fixtures/files/default.jpg",
    "test/fixtures/files/default.txt",
    "test/fixtures/files/default2.jpg",
    "test/fixtures/gallery/galleries.yml",
    "test/fixtures/gallery/photos.yml",
    "test/functional/admin/gallery/galleries_controller_test.rb",
    "test/functional/admin/gallery/photos_controller_test.rb",
    "test/functional/gallery/galleries_controller_test.rb",
    "test/test_helper.rb",
    "test/unit/configuration_test.rb",
    "test/unit/gallery_test.rb",
    "test/unit/photo_test.rb"
  ]
  s.homepage = "http://github.com/comfy/comfy-gallery"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "ComfyGallery is an image gallery engine for Rails 3.1 apps (and ComfortableMexicanSofa)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 1.0.14"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<paperclip>, [">= 2.3.0"])
      s.add_dependency(%q<jquery-rails>, [">= 1.0.14"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<paperclip>, [">= 2.3.0"])
    s.add_dependency(%q<jquery-rails>, [">= 1.0.14"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

